### Week 5-2 NumPy Practice Problems

In [4]:
import numpy as np

### Warm up
NumPy creation and indexing.

In [10]:
# 1. Creates 3x3 array of zeros
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# 2. Creates array [0, 2, 4, 6, 8]
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [16]:
# 3. 5 evenly spaced numbers from 0 to 1
b = np.linspace(0,1,5)
print(b)

[0.   0.25 0.5  0.75 1.  ]


In [28]:
# Array indexing, Gets elements > 5
arr = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print(arr[arr>5])

[6 7 8 9]


### Problem 1
Convert an array of Celsius measurements to Fahrenheit.
Note: `fahrenheit = (Celsius * 9/5) + 32`.

In [30]:
def convert_to_fahrenheit_list(temperatures):
    return [n * 9/5 + 32 for n in temperatures]

In [32]:
print("Testing with a regular list:")
temps_list = [0, 10, 20, 30]
print(convert_to_fahrenheit_list(temps_list))

Testing with a regular list:
[32.0, 50.0, 68.0, 86.0]


In [34]:
def convert_to_fahrenheit_numpy_array(temperatures):
    return temperatures * 9/5 +32

In [36]:
print("\nTesting with a NumPy array:")
temps_array = np.array([0, 10, 20, 30])
print(convert_to_fahrenheit_numpy_array(temps_array))


Testing with a NumPy array:
[32. 50. 68. 86.]


### Problem 2
Use numpy to create a function that adds a border filled with zeros around an existing array.

*Hint*: Use numpy's `pad` function. See https://numpy.org/doc/stable/reference/generated/numpy.pad.html

Note: we did not cover this function in class, see if you are comfortable of reading numpy documents and learn on your own!

In [103]:
def add_border(x):
    return np.pad(x,1,mode='constant',constant_values=0)

In [105]:
x = np.ones((1, 1))
claimed = add_border(x)
correct = np.zeros((3, 3))
correct[1, 1] = 1.0
assert claimed.shape == correct.shape
assert np.all(np.abs(claimed - correct) < 1e-8)

### Problem 3
Create an $n \times n$ numpy array filled with a checkerboard pattern of zeros and ones. The first entry should be the integer `0`. Assume $n \ge 2$.

In [107]:
def make_checkerboard(n):
    row_idx = np.arange(n) # [n,1]
    col_idx = np.arange(n).reshape(n,1) # [n,1]
    return (row_idx + col_idx) % 2

In [109]:
correct = \
    [[0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0]]
assert np.all(correct == make_checkerboard(8))

In [111]:
import numpy as np
x = np.arange(10)